import type { Metadata } from "next";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";

//test
export const metadata: Metadata = {
  title: "Stamina Gym Fitness",
  description: "Generated by create next app",
  icons: {
    icon: "/Logo_v2.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >   
        {children}
       <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
}